name: Update that resume!

on: push

jobs:
  generate_cv_job:
    runs-on: ubuntu-latest
    name: A job to generate CV pdf on push
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile LaTeX document with pre/post compile actions
      uses: xu-cheng/latex-action@v3
      with:
        texlive_version: ${{ matrix.texlive_version }}
        root_file: resume.tex
        working_directory: src/
        pre_compile: |
          rm resume.pdf
        post_compile: |
          ls resume.pdf

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Updated Resume via GH Actions." -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
